### ISSUE TITLE
GetRecordsByFilter queries

### ISSUE THREAD

**Issue by Devvox93** [Tazmainiandevil/TableStorage.Abstractions#10]
Greetings Mr. Devil :)

First of all: thank you for your NuGet package!

I can see that you have provided a GetRecordsByFilter method to filter records.
In the Readme you explain it works by getting all records, which is true in the source as you literally use GetAllRecords().

There are query guidelines explained in the [Microsoft Docs ](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-design-guide#design-for-querying), from which I conclude that the earlier mentioned method uses a _table scan_.
It seems to me that the second or third option mentioned in the docs (range query or partition scan) would be more performant.
If that is true, the solution would be filter-methods for row keys (range query) and for properties (partition scan) to prevent table scans.

In my project I have accomplished this by using the GetByPartitionKey() and put a Where-clause on that because, as argumented above, I think this is more performant than using GetAllRecords().
_(I have a repository as a wrapper that calls your library, just in case implementations have to change in the future.)_

I am just getting started with Table Storage, so I wonder: Is my assumption correct and can this be improved (I'd gladly help with a PR) or am I thinking wrong?

**Comment by Tazmainiandevil** [comment]
Hi,
Glad you are making use of the library and it is helping you work with Table Storage. 

Firstly using GetByPartitionKey() followed by a Where-clause is a very performant way to get data and I would recommend this way.

Sometimes you have to interact with storage you cannot control or change the design to be more performant, also there may be a need for a search you run once every now and then. As you are aware Table Storage is not designed to query and filter it's data to the extent of other stores e.g. SQL Database. GetRecordsByFilter is designed for scenarios where a query is required and depending on data size at the trade off of performance. The method would perform a table scan but there are some tricks in there to try and improve that performance, one is using yield and another is deferred execution as well as the option to add a max record count. These combined can provide a performant mechanism to get data but the more data the slower the performance. 

Using the other mechanisms that are provided in TableStorage for filtering do not really lend themselves to generic cases and difficult to know if the query requires an "And" or "Or" and how many clauses, etc.. and there will always be a performance penalty for searches that do not have the partition key and/or the row key. Perhaps a way of injecting a custom data search might be something to look at.

I hope this makes sense and answers your questions.

Thanks,
Mark

**Comment by Devvox93** [comment]
Hi Mark,
It does and does not at the same time.

You say you recommend the way that I described the filtering, but it is unclear to me if you want to implement that in the library or not.
A simple "GetByPartitionKeyAndFilter()" and perhaps a docs note with the GetByFilter() method(s) that states that it will perform a table scan and the aforementioned method would perform better (depending on the amount of partitions) would seem a good followup to me.

Should I make a PR?
If you don't want to pick this up, I respect that and I can manage by using my current approach :)

**Comment by Tazmainiandevil** [comment]
Hi,

PR's are always welcome, the library is designed to make using Table Storage easier to use. Also any updates to documentation that is helpful it good.

I look forward to your PR :)

Thanks,
Mark

**Comment by Tazmainiandevil** [comment]
No movement on this or PRs so closing. This can be re-opened if there is something concrete to add
