### ISSUE TITLE
DeleteAllRecords()

### ISSUE THREAD

**Issue by ThomasPe** [Tazmainiandevil/TableStorage.Abstractions#11]
Hi, really enjoy your library.

I'm missing a way to clear an existing table of all records. Is this something you're planning on adding or would you accept a PR for this?

Cheers!

**Comment by Tazmainiandevil** [comment]
Hi,
To delete all at present you would have to get all records and then loop over each one calling delete. Or delete the table and recreate it, although there maybe a delay in doing that as the delete is not instant.

I hadn’t planned to add the functionality and PR’s are welcome.

Thanks,
Mark

**Comment by ThomasPe** [comment]
That's what I did (deleting records by PartitionKey) in my project, but I would be happy to share it since I need this myself from time to time. Thanks for the quick reply, will look into raising a PR then.

**Comment by Tazmainiandevil** [comment]
I look forward to your PR 😀👍

**Comment by ThomasPe** [comment]
Cool, thx for merging!
Any idea when you plan to update the nuget package? ☺

**Comment by Tazmainiandevil** [comment]
Getting that done today :)
