### ISSUE TITLE
Support With Azure.Data.Tables

### ISSUE THREAD

**Issue by AbdullahUtor** [Tazmainiandevil/TableStorage.Abstractions#14]
Microsoft.Azure.Cosmos.Table is absolute now can you please add support for Azure.Data.Tables

**Comment by Tazmainiandevil** [comment]
Thanks for raising this, I haven't had much time to devote to this library but I will be updating it soon :)

**Comment by Tazmainiandevil** [comment]
Update: @AbdullahUtor the code has been modified to support Azure.Data.Tables in a separate branch. I am running some performance tests and checks and aim to get a new version available by the end of the weekend.

**Comment by Tazmainiandevil** [comment]
Nuget package 3.3.0 is now available with the changes
