### ISSUE TITLE
Managed Identities

### ISSUE THREAD

**Issue by carlblanchard** [Tazmainiandevil/TableStorage.Abstractions#17]
Azure managed identities? it would be good if it could support tokenCredentials 

`c#
credential: new ChainedTokenCredential(new ManagedIdentityCredential()
                                                                    , new AzureCliCredential())
`
I've checked out the code and can send you a branch with this feature completed, I've tried to push a branch but keep getting 403 :(  - Do you need to add me as a contributor ? to be able to send branches and raise a pull request?

Thanks in advance.

**Comment by Tazmainiandevil** [comment]
Sorry didn't see this one. If you fork the repo you should be able to do a PR :)

**Comment by Tazmainiandevil** [comment]
Release 3.3.9 has support for Managed Identites
