### ISSUE TITLE
Cannot delete all data

### ISSUE THREAD

**Issue by heldersantovisma** [Tazmainiandevil/TableStorage.Abstractions#19]
I have a table that contains 304 records, if I use deleteallasync it throws an exception:
Exception while executing function: CrawlSnyk. Azure.Data.Tables: 99:The batch request operation exceeds the maximum 100 changes per change set.

I believe this operation needs to be done using batchs of 100 items.
Ex: https://github.com/ThomasPe/Azure.Data.Tables-Extensions/blob/main/src/Medienstudio.Azure.Data.Tables.Extensions/Extensions.cs

**Comment by Tazmainiandevil** [comment]
Thanks for raising this, Release 3.3.10 should have this issue fixed
