### ISSUE TITLE
Batch insert fails when batch size is too large

### ISSUE THREAD

**Issue by giometrix** [Tazmainiandevil/TableStorage.Abstractions#2]
Error returned from ATS emulator was

> The maximum number of operations allowed in one batch has been exceeded.

Here is test code to reproduce

```
var tableStore = new TableStore<TestTableEntity>("recordsbypartmaxpage", ConnectionString);
            var records = new List<TestTableEntity>();
            for (int i = 0; i < 1005; i++)
            {
               records.Add(new TestTableEntity(i.ToString(),"x"));
            }
            tableStore.Insert(records);
            tableStore.DeleteTable();
```

From the Azure Table Storage documentation ( https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.tablebatchoperation?view=azurestorage-8.1.3)

> A batch operation may contain up to 100 individual table operations, with the requirement that each operation entity must have same partition key. A batch with a retrieve operation cannot contain any other operations. Note that the total payload of a batch operation is limited to 4MB.

My suggestion would be to handle the former and don't worry about the latter.  In the vast majority of use cases 100 inserts of simple POCOs are going to be far less than 4MB, and the performance hit of trying to figure out how big the payload is would probably _not_ be worth it (in my opinion of course).

Let me know if you would like help on this.

**Comment by Tazmainiandevil** [comment]
Thanks for the update. I have added code to handle the 100 limit and I will close this issue
