### ISSUE TITLE
409 error after creating TableStore

### ISSUE THREAD

**Issue by GalayM** [Tazmainiandevil/TableStorage.Abstractions#5]
409 error after creating TableStore object where a table is Exist and options.EnsureTableExists is true.

**Comment by Tazmainiandevil** [comment]
Could you provide some more information for this issue.
I have ran the code in Framework and .NET Core with EnsureTableExists as true and called CreateTable and CreateTableAsync a number of times and did not receive a 409 conflict error.

**Comment by Tazmainiandevil** [comment]
Release 2.1.2 is now available on nuget.org

**Comment by GalayM** [comment]
Thank you!
